const { VITE_MOVIE_API_URL, VITE_EXPIRE_USER_HOURS, VITE_MOVIE_API_KEY, VITE_LOCATION_API_URL } =
  import.meta.env

export const EXPIRED_USER_HOURS = VITE_EXPIRE_USER_HOURS || '76'
export const MOVIE_KEY = VITE_MOVIE_API_KEY
export const MOVIE_API_URL = VITE_MOVIE_API_URL
export const LOCATION_API_URL = VITE_LOCATION_API_URL
